apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  namespace: karpenter
spec:
  amiFamily: AL2023  
  amiSelectorTerms:
    - alias: al2023@latest  # This is required in v1
  role: "KarpenterNodeRole-<CLUSTER-NAME>"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "<CLUSTER-NAME>"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "<CLUSTER-NAME>"
  kubelet:
    clusterDNS: ["10.100.0.10"]  # Required - replace with your cluster DNS IP
